[application]
name = "uncloud"
default_platform = "web"

[web.app]

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]


[[web.proxy]]
backend = "http://localhost:8080/api/"

[[web.proxy]]
backend = "http://localhost:8080/apps/"
