#!/usr/bin/env bash
set -euo pipefail

WORKSPACE_ROOT="$(cd "$(dirname "$0")" && pwd)"
WEB_CRATE="$WORKSPACE_ROOT/crates/uncloud-web"
DESKTOP_CRATE="$WORKSPACE_ROOT/crates/uncloud-desktop"
APP_DIR="$DESKTOP_CRATE/src-frontend/app"
DX_OUT="$WORKSPACE_ROOT/target/dx/uncloud-web/release/web/public"

echo "==> Building Dioxus web frontend..."
cd "$WEB_CRATE"
dx build --release

echo "==> Copying frontend bundle to Tauri dist..."
# Copy the Dioxus output directly into src-frontend/ so that root-relative
# asset paths (/assets/wasm/...) resolve correctly under tauri://localhost.
# preferences.html is not generated by Dioxus so it is preserved automatically.
find "$DESKTOP_CRATE/src-frontend" -mindepth 1 -not -name "preferences.html" -delete
cp -r "$DX_OUT/." "$DESKTOP_CRATE/src-frontend/"

echo "==> Building Tauri desktop app..."
cd "$WORKSPACE_ROOT"
cargo build -p uncloud-desktop

echo ""
echo "Done. Run with: cargo run -p uncloud-desktop"
